# Generated by Django 3.2.11 on 2022-01-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_qtd_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='variacao_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
